<?php

/**
 * This is the model base class for the table "user_top5_questions".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "UserTop5Questions".
 *
 * Columns in table "user_top5_questions" available as properties of the model,
 * followed by relations of table "user_top5_questions" available as properties of the model.
 *
 * @property integer $id
 * @property integer $vendor_id
 * @property string $question
 *
 * @property Users $vendor
 */
abstract class BaseUserTop5Questions extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'user_top5_questions';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'UserTop5Questions|UserTop5Questions', $n);
	}

	public static function representingColumn() {
		return 'question';
	}

	public function rules() {
		return array(
			array('vendor_id', 'numerical', 'integerOnly'=>true),
			array('question', 'safe'),
			array('vendor_id, question', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, vendor_id, question', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'vendor' => array(self::BELONGS_TO, 'Users', 'vendor_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'vendor_id' => null,
			'question' => Yii::t('app', 'Question'),
			'vendor' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('vendor_id', $this->vendor_id);
		$criteria->compare('question', $this->question, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}