<?php

/**
 * This is the model base class for the table "amazon_products".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "AmazonProducts".
 *
 * Columns in table "amazon_products" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $id
 * @property string $amazon_product_id
 * @property string $product_name
 * @property string $product_image
 * @property string $product_description
 * @property string $reviews
 * @property string $created_at
 * @property string $updated_at
 *
 */
abstract class BaseAmazonProducts extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'amazon_products';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'AmazonProducts|AmazonProducts', $n);
	}

	public static function representingColumn() {
		return 'reviews';
	}

	public function rules() {
		return array(
			array('amazon_product_id, product_name, product_image', 'length', 'max'=>255),
			array('reviews', 'length', 'max'=>10),
			array('product_description, created_at, updated_at', 'safe'),
			array('amazon_product_id, product_name, product_image, product_description, reviews, created_at, updated_at', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, amazon_product_id, product_name, product_image, product_description, reviews, created_at, updated_at', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'amazon_product_id' => Yii::t('app', 'Amazon Product'),
			'product_name' => Yii::t('app', 'Product Name'),
			'product_image' => Yii::t('app', 'Product Image'),
			'product_description' => Yii::t('app', 'Product Description'),
			'reviews' => Yii::t('app', 'Reviews'),
			'created_at' => Yii::t('app', 'Created At'),
			'updated_at' => Yii::t('app', 'Updated At'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('amazon_product_id', $this->amazon_product_id, true);
		$criteria->compare('product_name', $this->product_name, true);
		$criteria->compare('product_image', $this->product_image, true);
		$criteria->compare('product_description', $this->product_description, true);
		$criteria->compare('reviews', $this->reviews, true);
		$criteria->compare('created_at', $this->created_at, true);
		$criteria->compare('updated_at', $this->updated_at, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}