<?php

/**
 * This is the model base class for the table "event".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Event".
 *
 * Columns in table "event" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $event_title
 * @property string $event_image
 * @property integer $person_age
 * @property string $person_gender
 * @property string $address_1
 * @property string $address_2
 * @property string $city
 * @property integer $state_id
 * @property string $zip
 * @property string $additional_info
 * @property string $start_date
 * @property string $end_date
 * @property integer $start_time
 * @property integer $end_time
 *
 */
abstract class BaseEvent extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'event';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Event|Events', $n);
	}

	public static function representingColumn() {
		return 'person_gender';
	}

	public function rules() {
		return array(
			array('person_age, state_id, start_time, end_time', 'numerical', 'integerOnly'=>true),
			array('event_title, event_image, city, zip', 'length', 'max'=>255),
			array('person_gender', 'length', 'max'=>6),
			array('address_1, address_2, additional_info, start_date, end_date', 'safe'),
			array('event_title, event_image, person_age, person_gender, address_1, address_2, city, state_id, zip, additional_info, start_date, end_date, start_time, end_time', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, event_title, event_image, person_age, person_gender, address_1, address_2, city, state_id, zip, additional_info, start_date, end_date, start_time, end_time', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'event_title' => Yii::t('app', 'Event Title'),
			'event_image' => Yii::t('app', 'Event Image'),
			'person_age' => Yii::t('app', 'Person Age'),
			'person_gender' => Yii::t('app', 'Person Gender'),
			'address_1' => Yii::t('app', 'Address 1'),
			'address_2' => Yii::t('app', 'Address 2'),
			'city' => Yii::t('app', 'City'),
			'state_id' => Yii::t('app', 'State'),
			'zip' => Yii::t('app', 'Zip'),
			'additional_info' => Yii::t('app', 'Additional Info'),
			'start_date' => Yii::t('app', 'Start Date'),
			'end_date' => Yii::t('app', 'End Date'),
			'start_time' => Yii::t('app', 'Start Time'),
			'end_time' => Yii::t('app', 'End Time'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('event_title', $this->event_title, true);
		$criteria->compare('event_image', $this->event_image, true);
		$criteria->compare('person_age', $this->person_age);
		$criteria->compare('person_gender', $this->person_gender, true);
		$criteria->compare('address_1', $this->address_1, true);
		$criteria->compare('address_2', $this->address_2, true);
		$criteria->compare('city', $this->city, true);
		$criteria->compare('state_id', $this->state_id);
		$criteria->compare('zip', $this->zip, true);
		$criteria->compare('additional_info', $this->additional_info, true);
		$criteria->compare('start_date', $this->start_date, true);
		$criteria->compare('end_date', $this->end_date, true);
		$criteria->compare('start_time', $this->start_time);
		$criteria->compare('end_time', $this->end_time);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}