<?php

/**
 * This is the model base class for the table "country_master".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CountryMaster".
 *
 * Columns in table "country_master" available as properties of the model,
 * followed by relations of table "country_master" available as properties of the model.
 *
 * @property integer $id
 * @property string $country
 * @property string $country_code
 * @property string $country_code_iso3
 * @property integer $is_publish
 *
 * @property StateMaster[] $stateMasters
 * @property Users[] $users
 * @property Users1[] $users1s
 */
abstract class BaseCountryMaster extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'country_master';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'CountryMaster|CountryMasters', $n);
	}

	public static function representingColumn() {
		return 'country';
	}

	public function rules() {
		return array(
			array('is_publish', 'numerical', 'integerOnly'=>true),
			array('country', 'length', 'max'=>64),
			array('country_code', 'length', 'max'=>2),
			array('country_code_iso3', 'length', 'max'=>3),
			array('country, country_code, country_code_iso3, is_publish', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, country, country_code, country_code_iso3, is_publish', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'stateMasters' => array(self::HAS_MANY, 'StateMaster', 'country_id'),
			'users' => array(self::HAS_MANY, 'Users', 'country_id'),
			'users1s' => array(self::HAS_MANY, 'Users1', 'country_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'country' => Yii::t('app', 'Country'),
			'country_code' => Yii::t('app', 'Country Code'),
			'country_code_iso3' => Yii::t('app', 'Country Code Iso3'),
			'is_publish' => Yii::t('app', 'Is Publish'),
			'stateMasters' => null,
			'users' => null,
			'users1s' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('country', $this->country, true);
		$criteria->compare('country_code', $this->country_code, true);
		$criteria->compare('country_code_iso3', $this->country_code_iso3, true);
		$criteria->compare('is_publish', $this->is_publish);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}