<?php

/**
 * This is the model base class for the table "slider_image_management".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "SliderImageManagement".
 *
 * Columns in table "slider_image_management" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $caption
 * @property string $description
 * @property string $image_url
 * @property integer $type
 * @property integer $status
 * @property string $created_at
 * @property string $updated_at
 *
 */
abstract class BaseSliderImageManagement extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'slider_image_management';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'SliderImageManagement|SliderImageManagements', $n);
	}

	public static function representingColumn() {
		return 'caption';
	}

	public function rules() {
		return array(
			array('type, status', 'numerical', 'integerOnly'=>true),
			array('caption, image_url', 'length', 'max'=>255),
			array('description, created_at, updated_at', 'safe'),
			array('caption, description, image_url, type, status, created_at, updated_at', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, caption, description, image_url, type, status, created_at, updated_at', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'caption' => Yii::t('app', 'Caption'),
			'description' => Yii::t('app', 'Description'),
			'image_url' => Yii::t('app', 'Image Url'),
			'type' => Yii::t('app', 'Type'),
			'status' => Yii::t('app', 'Status'),
			'created_at' => Yii::t('app', 'Created At'),
			'updated_at' => Yii::t('app', 'Updated At'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('caption', $this->caption, true);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('image_url', $this->image_url, true);
		$criteria->compare('type', $this->type);
		$criteria->compare('status', $this->status);
		$criteria->compare('created_at', $this->created_at, true);
		$criteria->compare('updated_at', $this->updated_at, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}