<?php

/**
 * This is the model base class for the table "user_videos".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "UserVideos".
 *
 * Columns in table "user_videos" available as properties of the model,
 * followed by relations of table "user_videos" available as properties of the model.
 *
 * @property integer $id
 * @property integer $user_id
 * @property string $video_image
 * @property string $video_url
 *
 * @property Users $user
 */
abstract class BaseUserVideos extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'user_videos';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'UserVideos|UserVideoses', $n);
	}

	public static function representingColumn() {
		return 'video_image';
	}

	public function rules() {
		return array(
			array('user_id', 'numerical', 'integerOnly'=>true),
			array('video_image, video_url', 'length', 'max'=>255),
			array('user_id, video_image, video_url', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, user_id, video_image, video_url', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'user' => array(self::BELONGS_TO, 'Users', 'user_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'user_id' => null,
			'video_image' => Yii::t('app', 'Video Image'),
			'video_url' => Yii::t('app', 'Video Url'),
			'user' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('video_image', $this->video_image, true);
		$criteria->compare('video_url', $this->video_url, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}