<?php

/**
 * This is the model base class for the table "amazon_products_categories".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "AmazonProductsCategories".
 *
 * Columns in table "amazon_products_categories" available as properties of the model,
 * followed by relations of table "amazon_products_categories" available as properties of the model.
 *
 * @property string $id
 * @property string $product_id
 * @property integer $category_id
 *
 * @property AmazonProducts $product
 * @property Category $category
 */
abstract class BaseAmazonProductsCategories extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'amazon_products_categories';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'AmazonProductsCategories|AmazonProductsCategories', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('category_id', 'numerical', 'integerOnly'=>true),
			array('product_id', 'length', 'max'=>20),
			array('product_id, category_id', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, product_id, category_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'product' => array(self::BELONGS_TO, 'AmazonProducts', 'product_id'),
			'category' => array(self::BELONGS_TO, 'Category', 'category_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'product_id' => null,
			'category_id' => null,
			'product' => null,
			'category' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('product_id', $this->product_id);
		$criteria->compare('category_id', $this->category_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}