<?php

/**
 * This is the model base class for the table "user_photos".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "UserPhotos".
 *
 * Columns in table "user_photos" available as properties of the model,
 * followed by relations of table "user_photos" available as properties of the model.
 *
 * @property integer $id
 * @property integer $user_id
 * @property string $photo_url
 *
 * @property Users $user
 */
abstract class BaseUserPhotos extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'user_photos';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'UserPhotos|UserPhotoses', $n);
	}

	public static function representingColumn() {
		return 'photo_url';
	}

	public function rules() {
		return array(
			array('user_id', 'required'),
			array('user_id', 'numerical', 'integerOnly'=>true),
			array('photo_url', 'length', 'max'=>255),
			array('photo_url', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, user_id, photo_url', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'user' => array(self::BELONGS_TO, 'Users', 'user_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'user_id' => null,
			'photo_url' => Yii::t('app', 'Photo Url'),
			'user' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('photo_url', $this->photo_url, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}