<?php

/**
 * This is the model base class for the table "category".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Category".
 *
 * Columns in table "category" available as properties of the model,
 * followed by relations of table "category" available as properties of the model.
 *
 * @property integer $id
 * @property integer $parent_id
 * @property string $category_name
 * @property string $category_image
 * @property string $category_type
 * @property string $category_description
 * @property integer $status
 * @property string $created_at
 * @property string $updated_at
 *
 * @property UserCategories[] $userCategories
 */
abstract class BaseCategory extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'category';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Category|Categories', $n);
	}

	public static function representingColumn() {
		return 'category_name';
	}

	public function rules() {
		return array(
			array('parent_id, status', 'numerical', 'integerOnly'=>true),
			array('category_name, category_image', 'length', 'max'=>255),
			array('category_type', 'length', 'max'=>6),
			array('category_description, created_at, updated_at', 'safe'),
			array('parent_id, category_name, category_image, category_type, category_description, status, created_at, updated_at', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, parent_id, category_name, category_image, category_type, category_description, status, created_at, updated_at', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'userCategories' => array(self::HAS_MANY, 'UserCategories', 'category_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'parent_id' => Yii::t('app', 'Parent'),
			'category_name' => Yii::t('app', 'Category Name'),
			'category_image' => Yii::t('app', 'Category Image'),
			'category_type' => Yii::t('app', 'Category Type'),
			'category_description' => Yii::t('app', 'Category Description'),
			'status' => Yii::t('app', 'Status'),
			'created_at' => Yii::t('app', 'Created At'),
			'updated_at' => Yii::t('app', 'Updated At'),
			'userCategories' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('parent_id', $this->parent_id);
		$criteria->compare('category_name', $this->category_name, true);
		$criteria->compare('category_image', $this->category_image, true);
		$criteria->compare('category_type', $this->category_type, true);
		$criteria->compare('category_description', $this->category_description, true);
		$criteria->compare('status', $this->status);
		$criteria->compare('created_at', $this->created_at, true);
		$criteria->compare('updated_at', $this->updated_at, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}